export const MDAS_LIST = [
    'Federal Ministry Of Industry, Trade And Investments',
    'National Population Commission',
    'Federal Ministry Of Youth & Sports Development - National Sports Commission',
    'Federal Ministry Of Youth & Sports Development - National Sports Commission - Hqtrs',
    'Federal Ministry Of Youth & Sports Development - Nigeria Institute For Sports (Nis)',
    'Federal Ministry Of Youth & Sports Development - Nigeria Football Association',
    'Federal Ministry Of Environment - Federal Ministry Of Environment',
    'Federal Ministry Of Environment - Yankari National Park',
    'Federal Ministry Of Environment - Special Climate Change Unit',
    'Federal Ministry Of Environment - Oyo National Park',
    'Federal Ministry Of Environment - Okumu National Park',
    'Federal Ministry Of Environment - National Park Headquarters',
    'Federal Ministry Of Environment - National Oil Spill Detection And Response Agency',
    'Federal Ministry Of Defence - Military Missons',
    'Federal Ministry Of Environment - National Environmental Standards And Regulations Enforcement Agency',
    'Federal Ministry Of Environment - Nag National Parks',
    'Federal Ministry Of Environment - Kamuku National Park',
    'Federal Ministry Of Environment - Kainji National Park',
    'Federal Ministry Of Environment - Gashaka Gumti National Park',
    'Federal Ministry Of Environment - Forestry Research Institute Of Ibadan',
    'Federal Ministry Of Environment - Forestry Mechanisation College Afaka',
    'Federal Ministry Of Environment - Federal Ministry Of Environmnt Headquarters',
    'Federal Ministry Of Environment - Federal College Of Wildlife Management - New Bussa',
    'Federal Ministry Of Environment - Federal College Of Forestry Ibadan',
    'Federal Ministry Of Defence - Guards Brigade',
    'Federal Ministry Of Environment - Federal Collecge Of Forestry Jos',
    'Federal Ministry Of Environment - Environmental Health Registration Council Of Nigeria',
    'Federal Ministry Of Environment - Cross River National Park',
    'Federal Ministry Of Environment - Chad Basin Natioal Park',
    'Federal Ministry Of Health - Federal Ministry Of Health',
    'Federal Ministry Of Health - Radiographers Registration Board',
    'Federal Ministry Of Health - Post Health Services (Phs)',
    'Federal Ministry Of Defence - Federal Ministry Of Defence - Main Hqtrs',
    'Federal Ministry Of Defence - Directorate Of Military Pensions',
    'Federal Ministry Of Health - Phc Tutors Programme,Uch-Ibadan',
    'Federal Ministry Of Health - Phc Tutors Programme,Kaduna Ply-Kaduna',
    'Federal Ministry Of Health - Pharmacist Council Of Nigeria Council',
    'Federal Ministry Of Health - Optometrist And Dispensing Opticians Board Of Nigeria',
    'Federal Ministry Of Health - Nursing And Midwifery Council',
    'Federal Ministry Of Health - Nurse Tutor Trainning Kaduna',
    'Federal Ministry Of Health - Nurse Tutor Trainning Ibadan',
    'Federal Ministry Of Defence - Defence Missions',
    'Federal Ministry Of Health - Nurse Tutor Training - Enugu',
    'Federal Ministry Of Health - Nurse Tutor Programme Akoka Lagos',
    'Federal Ministry Of Health - Noma Children Hospital, Sokoto',
    'Federal Ministry Of Health - Nigerian Institute Of Medical Research, Yaba',
    'Federal Ministry Of Health - National Programme On Immunization',
    'Federal Ministry Of Health - National Primary Health Care Development Agency',
    'Federal Ministry Of Health - National Post Graduate Medical College Of Nigeria-Ijanikin Lagos',
    'Federal Ministry Of Health - National Inst. Of Pharm. Research And Development, Abuja',
    'Federal Ministry Of Health - National Health Insurance Scheme',
    'Federal Ministry Of Health - National Health Equipment Training Centres -Zaria',
    'Federal Ministry Of Health - National Health Equipment Training Centres - Enugu',
    'Federal Ministry Of Health - National Health Equipment Training Centers (Nhetc)',
    'Federal Ministry Of Health - National Ear Care Centre',
    'Federal Ministry Of Health - National Arbovirus And Vector Research',
    'Federal Ministry Of Health - National Agency For Food And Drug Administration And Control',
    'Federal Ministry Of Health - Medical Rehabilitation Therapy Board',
    'Federal Ministry Of Health - Medical Lab. Science Council Of Nigeria, Yaba',
    'Federal Ministry Of Health - Medical And Dental Council Of Nigeria',
    'Federal Ministry Of Health - Institute Of Public Analysts Of Nigeria',
    'Federal Ministry Of Health - Institute Of Forensics Science Laboratory-Oshodi',
    'Federal Ministry Of Health - Institute Of Chartered Chemists Of Nigeria',
    'Federal Ministry Of Health - Institute For Child Health',
    'Federal Ministry Of Health - Health Records Registration Board',
    'Federal Ministry Of Health - Federal University Teaching Hospital',
    'Presidency - Code Of Conduct Tribunal',
    'Federal Ministry Of Health - Federal Staff Clinics',
    'Federal Ministry Of Health - Federal School Of Physiotheraphy - Kano',
    'Federal Ministry Of Health - Federal School Of Occupational Therapy, Yaba',
    'Federal Ministry Of Health - Federal School Of Dental Technology And Therapy, Enugu',
    'Federal Ministry Of Health - Federal Medical Centres',
    'Federal Ministry Of Health - Federal Federal Ministry Of Health - Hqtrs',
    'Federal Ministry Of Health - Environmental Health Officers Tutors-Ibadan',
    'Federal Ministry Of Health - Dental Therapists Registration Board',
    'Federal Ministry Of Health - Dental Technology Registration Board',
    'Federal Ministry Of Health - Community Health Tutor Programme Uch',
    'Federal Ministry Of Health - Community Health Practitoners Registration Board',
    'Federal Ministry Of Health - Board Of Psychiatric Hospital',
    'Federal Ministry Of Health - Board Of Orthopaedic Hospital',
    'Federal Ministry Of Education - Federal Ministry Of Education',
    'Federal Ministry Of Education - West African Examination Council (Local)',
    'Federal Ministry Of Education - West African Examination Council (International)',
    'Federal Ministry Of Education - Universal Basic Education (Ube) Commission',
    'Federal Ministry Of Education - Teachers Registration Council Of Nigeria',
    'Federal Ministry Of Education - Nomadic Education Commission',
    'Federal Ministry Of Education - Nigerian Institute For Education Planners & Administration',
    'Federal Ministry Of Education - National Universities Commission Secretariat',
    'Federal Ministry Of Education - National Teachers Institute',
    'Federal Ministry Of Education - National Open University',
    'Presidency - Code Of Conduct Bureau',
    'Federal Ministry Of Education - National Library Of Nigeria',
    'Federal Ministry Of Education - National Examinations Council',
    'Federal Ministry Of Education - National Education Research & Development Council',
    'Federal Ministry Of Education - National Commission For College Education Secretariat',
    'Federal Ministry Of Education - National Business And Technical Education Board',
    'Federal Ministry Of Education - Mass Literacy Council',
    'Federal Ministry Of Education - Joint Admissions Matriculation Board',
    'Federal Ministry Of Education - Federal Universities',
    'Federal Ministry Of Defence - Defence Intelligence School',
    'Federal Ministry Of Defence - Defence Intelligence Agency',
    'Federal Ministry Of Education - Federal Unity School',
    'Federal Ministry Of Defence - Defence Industries Corporation Of Nigeria (Dicon)',
    'Federal Ministry Of Defence - Defence Headqurters',
    'Federal Ministry Of Defence - Command And Staff College, Jaji',
    'National Assembly - National Assembly',
    'National Assembly - Senate Committee On Public Accounts',
    'National Assembly - Senate',
    'National Assembly - National Assembly Commission',
    'Presidency - Centre For Management Development (Cmd)',
    'National Assembly - Nass Management',
    'National Assembly - Legislative Aides',
    'National Assembly - House Of Representatives',
    'Federal Ministry Of Education - Federal Polytechnic',
    'National Assembly - House Committee On Public Accounts',
    'National Assembly - General Service Office',
    'Presidency - Presidency',
    'Federal Ministry Of Education - Federal Ministry Of Education - Hqtrs',
    'Federal Ministry Of Education - Federal College Of Education',
    'Presidency - Utitlities Charges Commission',
    'Presidency - State House - Hqtrs',
    'Federal Ministry Of Education - Education Tax Fund',
    'Federal Ministry Of Education - Division Of Agricultural College, Abu Zaria',
    'Federal Ministry Of Education - Computer Registration Council Of Nigeria',
    'Federal Ministry Of Education - Committee Of Vice Chancellors',
    'Federal Ministry Of Education - College Of Petroleum And Gas Engineering, Effurun',
    'Federal Ministry Of Women Affairs - Federal Ministry Of Women Affairs',
    'Presidency - Special Services Office',
    'Federal Ministry Of Women Affairs - National Centre For Women Development',
    'Federal Ministry Of Women Affairs - Federal Ministry Of Women Affairs - Hqtrs',
    'Federal Ministry Of Youth & Sports Development - Federal Ministry Of Youth Development',
    'Federal Ministry Of Youth & Sports Development - National Youth Service Corps (Nysc)',
    'Federal Ministry Of Youth & Sports Development - Federal Ministry Of Youth Development - Hqtrs',
    'Federal Ministry Of Youth & Sports Development - Citizenship And Leadership Training Centre',
    'Federal Ministry Of Niger Delta - Federal Ministry Of Niger Delta',
    'Federal Ministry Of Niger Delta - Niger Delta Development Commission',
    'Federal Ministry Of Niger Delta - Federal Ministry Of Niger Delta Hqtrs',
    'Federal Capital Territory Administration - Federal Capital Territory Administration',
    'Presidency - Special Duties Office',
    'Presidency - Cabinet Secretariat',
    'Independent Corrupt Practices And Related Offences Commission - Independent Corrupt Practices And Related Offences Commission',
    'Federal Ministry Of Justice - Federal Ministry Of Justice',
    'Federal Ministry Of Justice - Regional Centre For Int&sq;L Commercial Arbitration',
    'Federal Ministry Of Justice - Nigerian Law School',
    'Federal Ministry Of Justice - Nigerian Law Reform Commission',
    'Federal Ministry Of Justice - Nigerian Copyright Commission',
    'Federal Ministry Of Justice - Nigeria Institute Of Advanced Legal Studies',
    'Federal Ministry Of Justice - National Human Rights Commission',
    'Federal Ministry Of Justice - National Drug Law Enforcement Agency',
    'Federal Ministry Of Justice - National Agency For The Prohibition Of Traffic In Persons',
    'Presidency - Small And Meduim Enterprises Development Agency Of Nigeria (Smedan)',
    'Federal Ministry Of Justice - Legal Aid Council',
    'Federal Ministry Of Justice - Federal Ministry Of Justice - Hqtrs',
    'Federal Ministry Of Justice - Council Of Legal Education',
    'Federal Ministry Of Justice - Corrupt Practices And Related Offences Commission',
    'Federal Judiciary - Judiciary',
    'Federal Judiciary - Supreme Court Of Nigeria',
    'Federal Judiciary - Sharia Court Of Appeal ? Abuja',
    'Federal Judiciary - National Judicial Institute- Abuja',
    'Federal Judiciary - National Judicial Council- Abuja',
    'Federal Judiciary - National Industrial Court',
    'Presidency - Secretary To The Government Of The Federation (Sgf)',
    'Federal Judiciary - Judiciary Service Committee- F.C.T. Abuja',
    'Federal Judiciary - High Court Of Justice ? F.C.T. Abuja',
    'Federal Judiciary - Federal Judiciary Service Commission- Abuja',
    'Federal Judiciary - Federal High Court ? Lagos',
    'Federal Judiciary - Customary Court Of Appeal- Abuja',
    'Federal Judiciary - Court Of Appeal',
    'Federal Ministry Of Works, Power And Housing - Federal Ministry Of Lands, Housing & Urban Development',
    'Federal Ministry Of Works, Power And Housing - Urban Development Bank',
    'Federal Ministry Of Works, Power And Housing - Town Planners Registration Council',
    'Federal Ministry Of Works, Power And Housing - Quantity Surveyors Registration Board Of Nig',
    'Presidency - Revenue Mobilization, Allocation, And Fiscal Commission',
    'Federal Ministry Of Works, Power And Housing - Federal Mortgage Bank Of Nigeria',
    'Federal Ministry Of Works, Power And Housing - Federal Ministry Lands, Housing & Urban Development - Hqtrs',
    'Federal Ministry Of Works, Power And Housing - Federal Housing Authority',
    'Federal Ministry Of Works, Power And Housing - Estate Surveyors And Valuers Registration Board',
    'Federal Ministry Of Works, Power And Housing - Council For The Registration Of Builders Of Nig',
    'Federal Ministry Of Works, Power And Housing - Arcthitect Registration Board Of Niegria -Arcon',
    'Federal Ministry Of Water Resources - Federal Ministry Of Water Resources',
    'Federal Ministry Of Water Resources - Upper Niger Rbda',
    'Federal Ministry Of Water Resources - Upper Benue Rbda',
    'Federal Ministry Of Water Resources - Sokoto Rima Rbda',
    'Presidency - Presidential Advisory Committee',
    'Federal Ministry Of Water Resources - Ogun/ Osun Rbda',
    'Federal Ministry Of Water Resources - Nigeria Institute Of Oceanography And Marine Research (Niomr) - Lagos',
    'Federal Ministry Of Water Resources - Niger Delta Rbda',
    'Federal Ministry Of Water Resources - National Water Resources Institute- Kaduna',
    'Federal Ministry Of Water Resources - Lower Niger Rbda',
    'Federal Ministry Of Water Resources - Lower Benue Rbda',
    'Federal Ministry Of Water Resources - Lake Chad Research Institute- Maiduguri',
    'Federal Ministry Of Water Resources - Hadejia-Jama?Are Rbda',
    'Federal Ministry Of Water Resources - Federal Ministry Of Water Resources - Hqtrs',
    'Federal Ministry Of Water Resources - Cross River Rbda',
    'Presidency - Political Affairs Office',
    'Federal Ministry Of Water Resources - Chad Basin Rbda',
    'Federal Ministry Of Water Resources - Benin/ Owena Rbda',
    'Federal Ministry Of Water Resources - Anambra/ Imo Rbda',
    'Federal Ministry Of Information & Culture - Federal Ministry Of Tourism, Culture & National Orientation',
    'Federal Ministry Of Information & Culture - Nigerian Tourism Development Corporation',
    'Federal Ministry Of Information & Culture - National War Museum - Umuahia',
    'Federal Ministry Of Information & Culture - National Troupe Of Nigeria',
    'Federal Ministry Of Information & Culture - National Theatre',
    'Federal Ministry Of Information & Culture - National Orientation Agency',
    'Federal Ministry Of Information & Culture - National Institute For Culture Orientation',
    'Presidency - Petroleum Products Pricing Regulatory Agency (Ppra)',
    'Federal Ministry Of Information & Culture - National Inst. Of Hospitality And Tourism Development Studies',
    'Federal Ministry Of Information & Culture - National Gallery Of Art',
    'Federal Ministry Of Information & Culture - National Council Of Arts And Culture',
    'Federal Ministry Of Information & Culture - National Commission For Museums And Monuments',
    'Federal Ministry Of Information & Culture - Institute Of Archeology And Museum Studies- Jos',
    'Federal Ministry Of Information & Culture - Hotel And Catering School Lagos',
    'Federal Ministry Of Information & Culture - Hotel And Catering School Kaduna',
    'Federal Ministry Of Information & Culture - Hotel And Catering School - Enugu',
    'Federal Ministry Of Information & Culture - Hotel And Catering School - Benin',
    'Federal Ministry Of Information & Culture - Federal Ministry Of Tourism, Culture & National Orientation - Hqtrs',
    'Presidency - Pension Area Office',
    'Federal Ministry Of Information & Culture - Centre For Black African Arts And Civilisation',
    'Federal Ministry Of Works, Power And Housing - Federal Ministry Of Works',
    'Federal Ministry Of Works, Power And Housing - Survey Council Of Nigeria',
    'Federal Ministry Of Works, Power And Housing - Regional Centre For Training In Aerospace Survey',
    'Federal Ministry Of Works, Power And Housing - Office Of The Surveyor-General Of The Federation',
    'Federal Ministry Of Works, Power And Housing - Federal School Of Survey, Oyo',
    'Federal Ministry Of Works, Power And Housing - Federal Road Maintenance Agency',
    'Federal Ministry Of Works, Power And Housing - Council For The Regulation Of Engineering In Nigeria (Coren)',
    'Federal Ministry Of Solid Minerals Development - Federal Ministry Of Mines And Steel Development',
    'Presidency - Office Of The Special Adviser, Senior Special Assistants, And Special Assistants To The President Domiciled In The State House',
    'Federal Ministry Of Solid Minerals Development - Nigerian Geological Survey Agency.',
    'Federal Ministry Of Solid Minerals Development - National Steel Raw Materials Exploration Agency, Kaduna',
    'Federal Ministry Of Solid Minerals Development - National Metallurgical Development Centre, Jos',
    'Federal Ministry Of Solid Minerals Development - National Iron Ore Mining Project - Itakpe',
    'Federal Ministry Of Solid Minerals Development - Metallurgical Training Institute, Onitsha',
    'Federal Ministry Of Solid Minerals Development - Federal Ministry Of Mines And Steel Dvelopment - Hqtrs',
    'Federal Ministry Of Solid Minerals Development - Council Of Nigerian Mining Engineers And Geosciences',
    'Federal Ministry Of Solid Minerals Development - African Iron And Steel Association',
    'Federal Ministry Of Petroluem Resources - Federal Ministry Of Petroluem Resources',
    'Federal Ministry Of Petroluem Resources - Petroleum Training Institute',
    'Presidency - Office Of The Senior Special Assistant To The President - Mdgs (Ossap-Mdgs)',
    'Federal Ministry Of Petroluem Resources - Petroleum Resources (Gas Sector)',
    'Federal Ministry Of Petroluem Resources - Petroleum Equalization Fund',
    'Federal Ministry Of Petroluem Resources - Nigeria Nuclear Regulatory Agency',
    'Federal Ministry Of Petroluem Resources - Minsitry Of Energy (Petroleum Resources) Hqtrs',
    'Federal Ministry Of Petroluem Resources - Department Of Petroleum Resources',
    'Federal Ministry Of Works, Power And Housing - Federal Ministry Of Power',
    'Federal Ministry Of Works, Power And Housing - Power Holding Company Of Nigeria',
    'Federal Ministry Of Works, Power And Housing - Nigerian Electricity Regulatory Commission',
    'Federal Ministry Of Works, Power And Housing - Niger Delta Power Holding Company/National Integrated Power Project',
    'Federal Ministry Of Works, Power And Housing - National Rural Electrification Agency',
    'Presidency - Office Of The Head Of The Civil Service Of The Federation',
    'Presidency - Bureau Of Public Service Reforms',
    'Federal Ministry Of Works, Power And Housing - Mambilla Hydro-Electric Power Project',
    'Federal Ministry Of Works, Power And Housing - Federal Ministry Of Energy (Power) - Hqtrs',
    'Federal Ministry Of Works, Power And Housing - Energy Commission Of Nigeria',
    'Federal Ministry Of Works, Power And Housing - Centre For Energy Research - Sokoto',
    'Federal Ministry Of Works, Power And Housing - Centre For Energy Research - Nsukka',
    'Federal Ministry Of Transport - Federal Ministry Of Aviation',
    'Federal Ministry Of Transport - Nigerian College Of Aviation Technology-Zaria',
    'Federal Ministry Of Transport - Nigeria Metrological Services (Nimet)',
    'Federal Ministry Of Transport - Nigeria Airspace Management Agency',
    'Federal Ministry Of Transport - Federal Ministry Of Aviation - Hqtrs',
    'Federal Ministry Of Transport - Federal Airport Authority Of Nigeria',
    'Federal Ministry Of Transport - Aviation Sector (Air Transport)',
    'Federal Ministry Of Transport - Accident Investigation Bureau',
    'Federal Ministry Of Transport - Federal Ministry Of Transport',
    'Federal Ministry Of Transport - Port Security',
    'Federal Ministry Of Transport - Nigerian Railway Corporation',
    'Federal Ministry Of Transport - Nigerian Institute Of Transport Technology',
    'Federal Ministry Of Transport - Nigeria Shipper Council',
    'Federal Ministry Of Transport - Nigeria Railways Hospitals',
    'Federal Ministry Of Transport - National Inland Waterways Authority',
    'Federal Ministry Of Transport - Maritime Academy, Oron',
    'Federal Ministry Of Transport - Federal Federal Ministry Of Transport - Hqtrs',
    'Federal Ministry Of Transport - Council For The Regulation Of Freight Forwarding In Nigeria',
    'Federal Ministry Of Science And Technology - Federal Ministry Of Science And Technology',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Yola',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Yenegoa',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Warri',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Uyo',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Sokoto',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Okwe Onuimo',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Nnewi',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Minna',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Maiduguri',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Kano',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Jos',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Igbotako',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Ibadan',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Gusau',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Calabar',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Benin',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Bauchi',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - B/ Kebbi',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Agege',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Abeokuta',
    'Federal Ministry Of Science And Technology - Technology Business Incubator Centre - Aba',
    'Federal Ministry Of Science And Technology - Sheda Science And Technology Complex - Abuja',
    'Federal Ministry Of Science And Technology - Science Equipment Development Intitute - Minna',
    'Federal Ministry Of Science And Technology - Science Equipment Development Institute- Enugu',
    'Federal Ministry Of Science And Technology - Regional Centre For Technonogy Management (Nacetem - Lagos)',
    'Federal Ministry Of Science And Technology - Project Development Institute - Enugu',
    'Federal Ministry Of Science And Technology - Power Equipment And Electrical Machinery Development Centre - Okene',
    'Federal Ministry Of Science And Technology - Nigerian Building And Road Research Institute - Lagos',
    'Federal Ministry Of Science And Technology - Nigeria Nuclear Regulatory Authority',
    'Federal Ministry Of Science And Technology - Nigeria Natural Medicine Development Agency',
    'Federal Ministry Of Science And Technology - Nigeria Maritime Security And Administrative Agency',
    'Federal Ministry Of Science And Technology - Nigeria Institute For Science Laboratory Technology - Ibadan',
    'Federal Ministry Of Science And Technology - National Space Research And Development Agency - Abuja',
    'Federal Ministry Of Science And Technology - National Research Institute For Chemical Technology -Zaria',
    'Federal Ministry Of Science And Technology - National Office Of Technology Acquisition And Promotion - Abuja',
    'Federal Ministry Of Science And Technology - National Institute Trypanosomiasis Research - Kaduna',
    'Federal Ministry Of Science And Technology - National Engineering Design And Development Centre -Nnewi',
    'Federal Ministry Of Science And Technology - National Centre For Technonogy Management Ile Ife',
    'Federal Ministry Of Science And Technology - National Centre For Remote Sensing - Jos',
    'Federal Ministry Of Science And Technology - National Centre For Genetic Research And Biotechnology - Ibadan',
    'Federal Ministry Of Science And Technology - National Biotechnological Development Agency - Abuja',
    'Federal Ministry Of Science And Technology - National Atomic Energy Commission & Centres',
    'Federal Ministry Of Science And Technology - National Agency For Science And Engineering Infrastructures',
    'Federal Ministry Of Science And Technology - Hydraulic Equipment Research Institute - Kano',
    'Federal Ministry Of Science And Technology - Federal Ministry Of Science And Technology - Hqtrs',
    'Federal Ministry Of Science And Technology - Federal Institute Of Industrial Research -Oshodi',
    'Presidency - Federal Ministry Of Special Duties (Sgf)',
    'Federal Ministry Of Science And Technology - Engineering Materials Development Institute - Akure',
    'Federal Ministry Of Science And Technology - Cooperative Information Network',
    'Federal Ministry Of Science And Technology - College Of Chemical And Leather Technology - Zaria',
    'Federal Ministry Of Science And Technology - Centre For Space Transport And Propulsion, Epe-Lagos',
    'Federal Ministry Of Science And Technology - Centre For Satellite Technology Development - Abuja',
    'Federal Ministry Of Science And Technology - Centre For Geodesy And Geodynamics Toro Bauchi',
    'Federal Ministry Of Science And Technology - Centre For Basic Space Science Nsukka Enugu State',
    'Federal Ministry Of Science And Technology - Centre For Adaptation Of Technology - Awka (Eldi Awka)',
    'Federal Ministry Of Science And Technology - Board For Technology Business Incubator Centre - Abuja',
    'Federal Ministry Of Science And Technology - Africa Regional Centre For Space Science & Technology - Ile-Ife',
    'Presidency - National Institute For Policy And Strategic Studies (Nipss)',
    'Federal Ministry Of Communication Technology - Federal Ministry Of Communication Technology',
    'Federal Ministry Of Communication Technology - Nipost',
    'Federal Ministry Of Communication Technology - Nigeria Communication Satellite Limited',
    'Federal Ministry Of Communication Technology - Nigeria Communication Commission',
    'Federal Ministry Of Communication Technology - National Information Technology Development Agency',
    'Federal Ministry Of Communication Technology - Galaxy Backbone Limited',
    'Federal Ministry Of Communication Technology - Federal Ministry Of Communication Technology - Hqtrs',
    'Federal Ministry Of Labour And Employment - Federal Ministry Of Labour And Productivity',
    'Federal Ministry Of Labour And Employment - Skill Acquisition And Training',
    'Federal Ministry Of Labour And Employment - National Productivity Centre',
    'Presidency - Nigeria Institute Of International Affairs',
    'Federal Ministry Of Labour And Employment - National Directorate Of Employment',
    'Federal Ministry Of Labour And Employment - Michael Imodu Institute Of Labour Studies',
    'Federal Ministry Of Labour And Employment - Industrial Arbitration Panel',
    'Federal Ministry Of Labour And Employment - Federal Ministry Of Labour And Productivity - Hqtrs',
    'Federal Ministry Of Industry, Trade And Investments - Federal Ministry Of Commerce And Industry',
    'Federal Ministry Of Industry, Trade And Investments - Weight And Measure Training Institute',
    'Federal Ministry Of Industry, Trade And Investments - Trade Fair Complex, Lagos',
    'Federal Ministry Of Industry, Trade And Investments - Tafawa Balewa Square Management Board',
    'Federal Ministry Of Industry, Trade And Investments - Standard Organization Of Nigeria',
    'Federal Ministry Of Industry, Trade And Investments - Onne Oil And Gas Free Zone Authority',
    'Presidency - Nigeria Extractive Industries Transparency Initiative (Neiti)',
    'Presidency - Bureau Of Public Procurement (Bpp)',
    'Federal Ministry Of Industry, Trade And Investments - Nmt',
    'Federal Ministry Of Industry, Trade And Investments - Nigerian Investment Promotion Commission',
    'Federal Ministry Of Industry, Trade And Investments - Nigerian Export Promotion Council',
    'Federal Ministry Of Industry, Trade And Investments - Nigerian Export Processing Zones Authority',
    'Federal Ministry Of Industry, Trade And Investments - Nigerian Accounting Standards Board',
    'Federal Ministry Of Industry, Trade And Investments - Nigeria Trade Office, Taiwan',
    'Federal Ministry Of Industry, Trade And Investments - Nigeria Trade Office, China',
    'Federal Ministry Of Industry, Trade And Investments - National Sugar Development Council',
    'Federal Ministry Of Industry, Trade And Investments - National Automotive Council',
    'Federal Ministry Of Industry, Trade And Investments - Industrial Training Fund',
    'Presidency - Nigeria Christian Pilgrim Commission',
    'Federal Ministry Of Industry, Trade And Investments - Federal Produce Inspection',
    'Federal Ministry Of Industry, Trade And Investments - Federal Ministry Of Industry And Commerce - Hqtrs',
    'Federal Ministry Of Industry, Trade And Investments - External Trade Sector, Geneva (Wto)',
    'Federal Ministry Of Industry, Trade And Investments - Corporate Affairs Commission',
    'Federal Ministry Of Industry, Trade And Investments - Consumer Protection Council',
    'Federal Ministry Of Industry, Trade And Investments - Commercial Desk - Geneva',
    'Federal Ministry Of Industry, Trade And Investments - Commercial Desk - China',
    'Federal Ministry Of Industry, Trade And Investments - Centre For Automotive Design And Development',
    'Federal Ministry Of Industry, Trade And Investments - Bacita Sugar',
    'Federal Ministry Of Industry, Trade And Investments - Arcedem',
    'Presidency - Nigereria Investment Promotion Council',
    'Federal Ministry Of Industry, Trade And Investments - Abuja Securities And Commodity Exchange Commission',
    'Federal Ministry Of Finance - Federal Ministry Of Finance',
    'Federal Ministry Of Finance - Security And Exchange Commission',
    'Federal Ministry Of Finance - Office Of The Accountant-General Of The Federation',
    'Presidency - National Partnership For Africa&sq;S Development (Nepad)',
    'Presidency - National Salaries, Income And Wages Commission',
    'Presidency - National Poverty Eradication Program (Napep)',
    'Federal Ministry Of Budget & National Planning - National Planning Commission',
    'Federal Ministry Of Finance - National Insurance Commission',
    'Federal Ministry Of Finance - National Board For Community Banks',
    'Federal Ministry Of Finance - Investment And Securities Tribunal',
    'Federal Ministry Of Finance - Federal Ministry Of Finance - Hqtrs',
    'Federal Ministry Of Finance - Federal Inland Revenue Services',
    'Federal Ministry Of Finance - Debt Management Office',
    'Federal Ministry Of Finance - Central Bank Of Nigeria',
    'Federal Ministry Of Budget & National Planning - Budget Office Of The Federation',
    'Federal Ministry Of Agriculture - Federal Ministry Of Agriculture And Water Resources',
    'Federal Ministry Of Agriculture - Veterinary Council Of Nigeria',
    'Federal Ministry Of Agriculture - Rubber Research Institute- Benin',
    'Federal Ministry Of Agriculture - Nigeria Stored Products Research, Ilorin',
    'Federal Ministry Of Agriculture - Nigeria Animal Institute',
    'Federal Ministry Of Agriculture - National Veterinary Research Institute- Vom',
    'Federal Ministry Of Agriculture - National Root Crops Research Institute- Umudike',
    'Federal Ministry Of Agriculture - National Institute Of Freshwater Fish- New Bussa',
    'Federal Ministry Of Agriculture - National Institute For Oil Palm Research (Nifor) - Benin',
    'Federal Ministry Of Agriculture - National Horticultural Research Institute- Ibadan',
    'Federal Ministry Of Agriculture - National Cereals Research Institute- Badeggi',
    'Federal Ministry Of Agriculture - National Centre For Agricultural Mechanisation- Ilorin',
    'Federal Ministry Of Agriculture - National Animal Product Research Institute- Zaria',
    'Federal Ministry Of Agriculture - National Agricultural Insurance Corporation (Naic)',
    'Federal Ministry Of Agriculture - National Agric. Extension Research Liaison Services- Zaria',
    'Federal Ministry Of Agriculture - Institute Of Agricultural Research- Zaria',
    'Federal Ministry Of Agriculture - Institute Of Agricultural Research And Training- Ibadan',
    'Federal Ministry Of Agriculture - Federal Ministry Of Agriculture',
    'Federal Ministry Of Agriculture - Federal Co-Operative College- Oji River',
    'Federal Ministry Of Agriculture - Federal Co-Operative College- Kaduna',
    'Federal Ministry Of Agriculture - Federal Co-Operative College- Ibadan',
    'Federal Ministry Of Agriculture - Federal College Of Produce Inspection And Stored Products Technology, Kano',
    'Federal Ministry Of Agriculture - Federal College Of Land Resources Technology, Kuru - Jos',
    'Federal Ministry Of Agriculture - Federal College Of Land Resources Technology - Owerri',
    'Federal Ministry Of Agriculture - Federal College Of Horticulture, Dadin-Kowa, Gombe',
    'Federal Ministry Of Agriculture - Federal College Of Fresh Water Fisheries Technology - New Bussa',
    'Federal Ministry Of Agriculture - Federal College Of Fresh Water Fisheries - Baga',
    'Federal Ministry Of Agriculture - Federal College Of Fisheries And Marine Technology - Lagos',
    'Presidency - National Pension Commission',
    'Presidency - Bureau Of Public Enterprises (Bpe)',
    'Federal Ministry Of Agriculture - Federal College Of Animal Health And Production Technology - Vom',
    'Federal Ministry Of Agriculture - Federal College Of Animal Health And Production Technology - Ibadan',
    'Federal Ministry Of Agriculture - Federal College Of Agriculture, Moore Plantation- Ibadan',
    'Federal Ministry Of Agriculture - Federal College Of Agriculture - Ishiagu',
    'Federal Ministry Of Agriculture - Federal College Of Agriculture - Akure',
    'Federal Ministry Of Agriculture - College Of Veterinary And Medical Laboratory Technology - Vom',
    'Federal Ministry Of Agriculture - Cocoa Research Institute- Ibadan',
    'Federal Ministry Of Agriculture - Agricultural Research And Management Institute (Armti) - Ilorin',
    'Independent National Electoral Commission - Independent National Electoral Commission',
    'Public Complaints Commission - Public Complaints Commission',
    'Presidency - National Merit Award',
    'Auditor General For The Federation - Auditor General For The Federation',
    'Federal Ministry Of Interior - Federal Ministry Of Interior',
    'Federal Ministry Of Interior - Police Service Commission',
    'Federal Ministry Of Interior - Police Pension Board',
    'Federal Ministry Of Interior - Police Formations And Command',
    'Presidency - National Identity Management Commission',
    'Presidency - National Hospital',
    'Presidency - National Hajj Commission Of Nigeria',
    'Presidency - National Emergency Management Agency (Nema)',
    'Federal Ministry Of Interior - Federal Ministry Of Interior - Hqtrs',
    'Federal Ministry Of Interior - Federal Fire Service',
    'Federal Ministry Of Interior - Custom, Immigration, Prison Pension Office (Cippo)',
    'Federal Ministry Of Interior - Civil Defence, Immigration And Prison Service Board (Cipb)',
    'Presidency - National Economic Intelligence Committee',
    'Federal Ministry Of Information& Culture - Federal Ministry Of Information',
    'Federal Ministry Of Information& Culture - Voice Of Nigeria',
    'Federal Ministry Of Information& Culture - Nigerian Television Authority',
    'Federal Ministry Of Information& Culture - Nigerian Film Corporation',
    'Federal Ministry Of Information& Culture - Nigeria Telecommunication',
    'Federal Ministry Of Information& Culture - Nigeria Press Council',
    'Federal Ministry Of Information& Culture - Nigeria Institute Of Public Relations',
    'Federal Ministry Of Information& Culture - News Agency Of Nigeria',
    'Federal Ministry Of Information& Culture - National Film Institute',
    'Federal Ministry Of Information& Culture - National Film Archives',
    'Presidency - National Commission For Refugees',
    'Federal Ministry Of Information& Culture - National Film And Vedio Censor Board',
    'Federal Ministry Of Information& Culture - National Broadcasting Commision',
    'Federal Ministry Of Information& Culture - Information Sector',
    'Federal Ministry Of Information& Culture - Federal Radio Corporation Of Nigeria',
    'Federal Ministry Of Information& Culture - Federal Ministry Of Information� - Hqtrs',
    'Federal Ministry Of Information& Culture - Federal Govt. Press',
    'Federal Ministry Of Information& Culture - Advertising Practioners Of Nigeria',
    'Federal Ministry Of Foreign Affairs - Federal Ministry Of Foreign Affairs',
    'Federal Ministry Of Foreign Affairs - Technical Aids Corps',
    'Federal Ministry Of Foreign Affairs - Overseas Missions',
    'Presidency - National Boundary Commission',
    'Presidency - National Action Committee On Aids (Naca)',
    'Presidency - Lagos Liaison Office',
    'Presidency - Border Communities Development Agency',
    'Presidency - Infrastructural Concessionary And Regulatory Commission',
    'Presidency - Fiscal Responsilibity Commission',
    'Presidency - Federal Civil Service Commission',
    'Presidency - Federal Character Commission',
    'Presidency - Establishment And Pension&sq;S Office',
    'Presidency - Energy Commission Of Nigeria And Other Energy Centres',
    'Federal Ministry Of Foreign Affairs - Nigerian Institute Of International Affairs, Lagos',
    'Federal Ministry Of Foreign Affairs - Institute For Peace And Conflict Resolution',
    'Federal Ministry Of Foreign Affairs - Foreign Service Academy (Fsa)',
    'Federal Ministry Of Foreign Affairs - Federal Ministry Of Foreign & Intergovernmental Affairs - Hqtrs',
    'Presidency - Economic Affairs Office',
    'Federal Ministry Of Foreign Affairs - Directorate Of Technical Coop. In Africa',
    'Federal Ministry Of Foreign Affairs - Directorate Of Pilgrims Affairs (Muslim)',
    'Federal Ministry Of Foreign Affairs - Directorate Of Pilgrims Affairs (Christian)',
    'Federal Ministry Of Defence - Federal Ministry Of Defence',
    'Federal Ministry Of Defence - Presidential Committee On Barracks Rehabilitation',
    'Federal Ministry Of Defence - Nigerian Defence College',
    'Federal Ministry Of Defence - Nigerian Defence Academy (Nda)',
    'Federal Ministry Of Defence - Nigerian Armed Forces Resettlement Centre, Lagos',
    'Presidency - Ecological Fund Office',
    'Presidency - Affairs Of Former Heads Of State',
    'Federal Ministry of Women Affairs',
    'Federal Ministry of Finance',
    'National Population Commission',
    'National Sport Commission',
    'Nigeria Customs',
    'Federal Ministry of Environment',
    'Federal Ministry of Health',
    'Federal Ministry of Education',
    'Federal Ministry of Youth Development',
    'Federal Ministry of Niger Delta',
    'Code of Conduct Bureau',
    'Federal Ministry of Justice',
    'Judiciary',
    'Federal Ministry of Housing & Urban Development',
    'Federal Ministry of Water Resources',
    'FISCAL Responsibility Commission',
    'Revenue Mobilization, Allocation and Fiscal Commission',
    'National Salaries, Income and wages Commission',
    'Federal Ministry of Information and Culture',
    'Federal Ministry of Works',
    'Federal Ministry of Mines and Steel Development',
    'Federal Ministry of Petroleum Resources',
    'Federal Ministry of Power',
    'Federal Ministry of Aviation',
    'Federal Ministry of Transport',
    'Federal Ministry of Science and Technology',
    'Federal Ministry of Labour and Productivity',
    'Federal Ministry of Commerce and Industry',
    'Federal Ministry of Agriculture and Rural Development',
    'Federal Character Commission',
    'Independent National Electoral Commission',
    'Federal Civil Service Commission',
    'Public Complaints Commission',
    'Office of the Auditor General of the Federation',
    'Office of the Head of the Civil Service of the Federation',
    'Federal Ministry of Interior',
    'Federal Ministry of Communication and Digital Economy',
    'Federal Ministry of Foreign Affairs',
    'Federal Ministry of Defence',
    'National Assembly'
];


